### ISSUE TITLE
Create demo virtual machine

### ISSUE THREAD

**Issue by rieder91** [mangei/onion-routing#30]
according to the assignment we need to provide a vmdk image which demos our solution

**Comment by Budddy** [comment]
information from TUWEL Forum:

Submission details for Topic 3
von Hochreiner Christoph - Donnerstag, 22. Januar 2015, 18:07
 
For the submission of Topic 3, we expect one VM which hosts the client (Originator), that is able to access the remaining cloud infrastructure.
Further we expect that all groups (with Topic3) provide their images/virtual machines (VMs) on EC2 and provide their IDs in the README.
Optionally you can also submit all other (e.g. directory node, ..) VM images during the final presentations.

Please just stop the VMs after your presentation so that we can check your implementation for the grading.

If there are any further question regarding the submission, feel free to ask.

br ~Christoph
